Traceback (most recent call last):
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\transformers\__init__.py", line 3861, in <module>
    raise OptionalDependencyNotAvailable()
transformers.utils.import_utils.OptionalDependencyNotAvailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Thesis\DKH-Thesis\src\inference_use_searched_evidences.py", line 5, in <module>
    from modules import NERConnector, EntitiesModule, BLIP2Connector, GPTConnector, GeminiConnector, ExternalRetrievalModule, EvidencesModule, Evidence, GPTVisionConnector, GeminiVisionConnector
  File "F:\Thesis\DKH-Thesis\src\modules\__init__.py", line 1, in <module>
    from .entities_module import NERConnector, EntitiesModule
  File "F:\Thesis\DKH-Thesis\src\modules\entities_module\__init__.py", line 1, in <module>
    from .connector.NER import NERConnector
  File "F:\Thesis\DKH-Thesis\src\modules\entities_module\connector\NER.py", line 1, in <module>
    from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\transformers\__init__.py", line 3863, in <module>
    from .utils import dummy_tf_objects
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\transformers\utils\dummy_tf_objects.py", line 579, in <module>
    class TFBlenderbotSmallForConditionalGeneration(metaclass=DummyObject):
KeyboardInterrupt
